
function getLocationObject(){
    return{
        originalBuildings:{
            "!Residential":[
                "Apartments",
                "Hotel",
                "Villa",
                "Mansion",
            ],
            "Shop":[
                "Food",
                "Clothing",
                "Construction",
                "Pet",
                "Electronics",
                "Cosmetics",
            ],
            "!Institute":[
                "Post office",
                "Town hall",
                "Prison",
                "Police station",
                "Army base",
                "Hospital",
                "University",
                "Museum",
                "Research",
                "Courthouse",
                "Church",
            ],
            "Industry":[
                "Power plant",
                "Water treatment",
                "Oil and gas",
                "Chemical",
                "Medtech",
                "Explosives",
                "Manufacturing",
                "Consumer goods",
                "Weapons",
                "Electronics",
                "Furniture",
                "Food processing",
            ],
            "!Business":[
                "Offices",
                "Stock exchange",
                "Bank",
                "Parking Garage",
                "Gas Station",
                "Mechanics shop",
            ],
            "!Recreation":[
                "Cinema",
                "Lasertag",
                "Sports arena",
                "Bar",
                "Restaurant",
                "Brothel",
                "Night club",
                "Park",
                "Pool house",
                "Theater",
                "Zoo",  
            ],
        },
        currentUsage:{
            "Abandoned":[
                "Crater",
                "Radiated",
                "Ooze infested",
                "Dormant androids",
            ],
            "a Mutant den":[
                "for Saurian/Cacti/Gator/Weirdo",
                "for Bears/Stilt striders/Kelp/Test dummies",
            ],
            "an Animal barrow":[
                "for Roach/Antlion/Crayfish/Eel",
                "for Dogs",
                "for Carcrab/Shellslug/Tick/Radscorpions",
            ],
            "a Tavern":[
                "and rest stop",
                "and inn",
                "and hotel",
                "and karaoke bar",
            ],
            "a Settlement":[
                "of mixed professions",
                "and Fruit farm",
                "of canned food scavengers",
                "of hunters",
                "of ranchers",
                "of tinkerers",
                "processing water",
                "running a church",
                "with a bustling trade post",
                "of artifact scavengers",
            ],
            "an Outlaw hideout":[
                "of raiders",
                "of brigands",
                "of cultists",
                "for a gogo gang",
                "for roller thugs",
                "cooking drugs",
            ],
        }
    }
}