function getLocationObject() {
  var fightersOfNote = [
    "Blade, zone cyborg",
    "Killswitch, drone striker",
    "Law, lone star",
    "Beetle, the titan shell",
    "Bonesaw, bloatlord butcher",
    "Spring Fist, the monk",
    "Zigzag Zoran, the elusive",
    "Nightowl",
    "Hot Stuff, sexy assasin",
  ];
  var raceDrivers = [
    "Grizzly Jamboree, mechanic City Bear",
    "Ultra, defunct android racing AI",
    "Cassian Quark, propulsion engineer",
    "Pure Nitro, famous eel rider",
    "Cherry Chase, of the valley",
    "Jhonny Proto, bike-human cyborg",
    "Bomber, the warlord",
    "Dawn of the Drift",
  ];
  var syntheticWanderers = [
    "Surge Donovan, mage hunter",
    "Koid, mercenary loner",
  ];
  var androidWanderers = [
    "Bmo, sentient gaming droid",
    "Jack, electrical utility droid",
    "Bob, translator droid",
    "Clown, sinister carneval mascot",
    "Victor, butler droid",
    "Kowalski, cop droid",
  ];
  var banditsOfNote = [""];
  return {
    any: {
      "Originally a": ["Food shop"],
      "Currently a": [
        {
          Name: "Mutant den",
          "Inhabited by": ["Roaches"],
        },
        {
          Name: "Animal burrow",
          "Inhabited by": ["Jellies"],
          Hoard: ["Stuff"],
        },
      ],
    },
    cityscape: {
      "Originally a": [
        "Food shop",
        "Apartments",
        "Hotel",
        "Villa",
        "Mansion",
        "Food shop",
        "Clothing shop",
        "Construction shop",
        "Pet shop",
        "Electronics shop",
        "Cosmetics shop",
        "Post office",
        "Town hall",
        "Prison",
        "Police station",
        "Army base",
        "Hospital",
        "University",
        "Museum",
        "Research",
        "Courthouse",
        "Church",
        "Power plant",
        "Water treatment",
        "Oil and gas refinery",
        "Chemical plant",
        "Medtech lab",
        "Explosives industry",
        "Assembly plant",
        "Consumer goods factory",
        "Weapons factory",
        "Electronics production",
        "Furniture factory",
        "Food processing plant",
        "Offices",
        "Stock exchange",
        "Bank",
        "Parking Garage",
        "Gas Station",
        "Mechanics shop",
        "Cinema",
        "Lasertag arena",
        "Sports arena",
        "Bar",
        "Restaurant",
        "Brothel",
        "Night club",
        "Park",
        "Pool house",
        "Theater",
        "Zoo",
        "Gundam Cafe",
        "Hobby Store",
        "Noodle Shop",
        "Foodcourt",
        "Cybercafe",
        "Marina",
        "Floating Restaurant",
        "Floating Market",
        "Greenhouse Plantation",
        "Bookstore",
        "Toystore",
        "Dancehall",
        "Bunker",
        "Windmill",
        "Bus Station",
        "Train Station",
        "Cat Cafe",
        "Plaza",
        "Outdoor market",
        "Dojo",
        "Boxing gym",
        "Gym",
      ],
      "Currently a": [
        {
          Name: "Mutant den",
          "Inhabited by": ["Saurians", "Sluggan", "Bears"],
          "Current Endeavor": ["Hunting", "Resting", "Fighting", "Working"],
        },
        {
          Name: ["Hideout", "Fortress"],
          "Inhabited by": [
            "Raiders",
            "Brigands",
            "Mercenaries",
            "Gogo gang",
            "Roller thugs",
          ],
          "Current Endeavor": [
            "Out on mission",
            "Preparing mission",
            "Celebrating success",
            "Mutiny after failure",
            "Resting",
            "Interrogating prisoners",
            "Producing drugs",
          ],
        },
        {
          Name: ["Tavern", "Karaoke bar", "Rest stop", "Hotel"],
          "Patrons of note": new GetSomeArray(
            [
              ...new GetAllArray(fightersOfNote).getList(),
              ...new GetAllArray(raceDrivers).getList(),
              ...new GetAllArray(syntheticWanderers).getList(),
              ...new GetAllArray(androidWanderers).getList(),
            ],
            4
          ),
          Event: ["Brawl", "Gambling", "Bloody Feud"],
        },
        {
          Name: "Animal burrow",
          "Inhabited by": ["Jellies", "Roid rats", "Albino Boarians"],
          Hoard: ["Stuff"],
        },
        {
          Name: ["Blood sport arena"],
          Fighters: [new GetSomeArray(fightersOfNote, 3)],
          Hoard: ["Stuff"],
        },
        {
          Name: ["Race Track"],
          "Patrons of note": [new GetSomeArray(raceDrivers, 2)],
          Hoard: ["Stuff"],
        },
        {
          Name: ["Gambling den", "Dogfighting pit"],
          "Patrons of note": [
            new GetSomeArray([...fightersOfNote, ...raceDrivers], 5),
          ],
          Hoard: ["Stuff"],
        },
        {
          Name: ["Crater", "Military base", "Research lab"],
          "Inhabited by": [
            "Saurians",
            "Sluggan explorers",
            "Dormant androids",
            "Strakers",
            "Abandoned",
          ],
          Hazard: ["Radiation", "Ooze", "Structural integrity"],
          Valuables: ["Artifacts", "Cybernetics", "Weapons", "Water reserve"],
        },
        {
          Name: ["Crater lake", "Filled Sinkhole", "River"],
        },
        {
          Name: ["Farm"],
          Produce: ["Fruit", "Roaches"],
          "Current problem": [
            "Kidnapped help",
            "Disease",
            "Sick family member",
          ],
          Demeanor: ["Cautious", "Afraid", "Confident", "Hopeless"],
        },
        {
          Name: ["Trade post", "Caravansery", "Black market"],
          "Inhabited by": ["Scavs", "Mixed traders from faraway", "Bandits"],
        },
        {
          Name: ["Shanty Town", "Settlement", "City"],
          "Inhabited by": [
            "Scavs",
            "Scavs",
            "Depriveds",
            "Depriveds",
            "Bandits",
            "Sluggan",
          ],
          Livelyhood: [
            "Farming",
            "Canned food scavenging",
            "Artifact scavenging",
            "Raw materials scavenging",
            "Vehicle scavenging",
            "Water purification",
            "Crafting",
            "Mixed",
            "Mechanics",
            "Weapons production",
            "Healthcare",
            "Chemistry and medicine",
          ],
          "Current Event": [
            "Hanging",
            "Preparation for raid",
            "Recent murder investigation",
            "Expedition preparation",
            "Riots",
            "Leadership coup",
          ],
        },
        {
          Name: ["Conclave"],
          "Inhabited by": ["True human"],
        },
        {
          Name: ["Temple", "Church", "Mosque", "Religious camp"],
          "Inhabited by": ["Nuke cultists", "Ooze cultists"],
        },
      ],
    },
    metro: {
      "Originally a": [
        "Convenience store",
        "Maintenance barracks",
        "Traffic central",
        "Ticket booth",
        "Train",
        "Food court",
        "Cosmetics store",
        "Gift shop",
        "Intersection",
      ],
      "Currently a": [
        {
          Name: "Mutant den",
          "Inhabited by": ["Strakers", "Bears", "Sluggan"],
        },
        {
          Name: "Animal burrow",
          "Inhabited by": ["Moledogs", "Roid Rats", "Albino Boarians"],
        },
        {
          Name: "Chasm",
          "Inhabited by": ["Olm", "Screamer Bats", "Necro Mutants"],
          Hazard: ["Flooding", "Brittle ground"],
        },
        {
          Name: "Rest stop",
          "Other visitors": [new WeightedValue(4, "None"), "Metroes", "Scavs"],
          Resources: [
            new WeightedValue(7, "None"),
            new WeightedValue(2, "Stuff"),
            "Weapon",
          ],
        },
      ],
    },
  };
}
