function getItems() {
  var items = [
    {
      name: "KNIFE",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["CUT", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/knife.jpg",
    },
    {
      name: "CRUDE SPEAR",
      type: "melee",
      usage: ["EFFECT", "QUALITY"],
      damageTypes: ["STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/spear.stone_512.png",
    },
    {
      name: "NUNCHAKU",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/nunchucks.png",
    },
    {
      name: "HARPOON",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/harpoon.png",
    },
    {
      name: "WOODEN CLUB",
      type: "melee",
      usage: ["QUALITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/club.png",
    },
    {
      name: "HAMMER",
      type: "melee",
      usage: ["QUALITY", "QUALITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/hammer.png",
    },
    {
      name: "CUTTER",
      type: "melee",
      usage: ["EFFECT", "QUALITY", "QUALITY"],
      damageTypes: ["CUT", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/cutter.png",
    },
    {
      name: "MACHETE",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "QUALITY", "DURABILITY", "QUALITY"],
      damageTypes: ["CUT", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/machete.png",
    },
    {
      name: "TORCH",
      type: "melee",
      usage: ["QUALITY", "DURABILITY"],
      damageTypes: ["LIGHT", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/torch.png",
    },
    {
      name: "LUMBER AXE",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["CUT", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/hatchet.png",
    },
    {
      name: "SHOVEL",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["CUT", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/shovel.png",
    },
    {
      name: "HUGE WRENCH",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/wrench.png",
    },
    {
      name: "SWORD",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "QUALITY", "DURABILITY", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["CUT", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/sword.png",
    },
    {
      name: "WHIP",
      type: "melee",
      usage: ["QUALITY", "QUALITY"],
      damageTypes: ["PAIN"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/whip.png",
    },
    {
      name: "TAZER",
      type: "melee",
      usage: ["QUALITY", "QUALITY"],
      damageTypes: ["VOLT", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/tazer.png",
    },
    {
      name: "GIANT CRUCIFIX",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "QUALITY", "DURABILITY"],
      damageTypes: ["LIGHT", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/cross.png",
    },
    {
      name: "BOLT STUNNER",
      type: "melee",
      usage: ["EFFECT", "DURABILITY", "QUALITY", "QUALITY"],
      damageTypes: ["GUN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/boltstunner.png",
    },
    {
      name: "MEAT CLEAVER",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["CUT"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/cleaver.png",
    },
    {
      name: "SCREWDRIVER",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/screwdriver.png",
    },
    {
      name: "CROWBAR",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/crowbar.png",
    },
    {
      name: "TIRE IRON",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/tireiron.jfif",
    },
    {
      name: "CLIMBING PICK",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/icepick.png",
    },
    {
      name: "BASEBALL BAT",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/bat.png",
    },
    {
      name: "HOCKEY CLUB",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/hockey.jpg",
    },
    {
      name: "CHAINSAW",
      type: "melee",
      usage: ["EFFECT", "EFFECT", "DURABILITY", "DURABILITY", "QUALITY", "QUALITY"],
      damageTypes: ["CUT", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/chainsaw.png",
    },
    {
      name: "CHAINSWORD",
      type: "melee",
      usage: ["EFFECT", "EFFECT", "DURABILITY", "DURABILITY", "QUALITY", "QUALITY", "QUALITY"],
      damageTypes: ["CUT", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/chainsword.png",
    },
    {
      name: "VIBROBLADE",
      type: "melee",
      usage: ["EFFECT", "DURABILITY", "QUALITY", "DURABILITY", "QUALITY", "QUALITY", "QUALITY", "DURABILITY", "QUALITY", "DURABILITY"],
      damageTypes: ["CUT"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/vibroblade.png",
    },
    {
      name: "NECRO CLEAVER",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "QUALITY"],
      damageTypes: ["CUT", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/chainaxe.png",
    },
    {
      name: "NECRO BLEEDER",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/necrobleeder.png",
    },
    {
      name: "GATOR BLADE",
      type: "melee",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "QUALITY", "QUALITY"],
      damageTypes: ["CUT", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/gatorblade.png",
    },
    {
      name: "POTS AND PANS",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/potsnpans.png",
    },
    {
      name: "FLASHLIGHT",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/flashlight.png",
    },
    {
      name: "ROPE",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: ["PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/rope.png",
    },
    {
      name: "CHAIN",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/grade-30-proof-coil-chain.jpg",
    },
    {
      name: "PORTABLE LADDER",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/ladder.png",
    },
    {
      name: "ARMY KNIFE",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH", "STAB", "CUT", "PAIN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/swissknife.png",
    },
    {
      name: "2X4",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/2x4Cedarklbs.jpg",
    },
    {
      name: "EXTINGUISHER",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/extinguisher.png",
    },
    {
      name: "BEAR TRAP",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "CUT", "PAIN", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/beartrap.png",
    },
    {
      name: "BOLT CUTTER",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/boltcutter.png",
    },
    {
      name: "PURE STAFF",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/purestaff.png",
    },
    {
      name: "SINISTER STAFF",
      type: "melee",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/sinisterstaff.png",
    },
    {
      name: "MOP",
      type: "melee",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/mop.png",
    },
    {
      name: "CROSSBOW",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/crossbow.png",
    },
    {
      name: "GATOR BOWGUN",
      type: "ranged",
      usage: ["EFFECT", "DURABILITY", "QUALITY", "DURABILITY"],
      damageTypes: ["STAB", "SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/gator-bowgun.png",
    },
    {
      name: "WRIST CANNON",
      type: "ranged",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/slingshot.png",
    },
    {
      name: "THROWING KNIVES",
      type: "ranged",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/knives.png",
    },
    {
      name: "COMPOUND BOW",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "DURABILITY"],
      damageTypes: ["STAB"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/bow.png",
    },
    {
      name: "MAKESHIFT PISTOL",
      type: "ranged",
      usage: ["EFFECT", "EFFECT", "QUALITY"],
      damageTypes: ["GUN"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/makeshiftpistol.png",
    },
    {
      name: "BERETTA",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "QUALITY"],
      damageTypes: ["GUN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/beretta.png",
    },
    {
      name: "MAGNUM",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "DURABILITY", "QUALITY"],
      damageTypes: ["GUN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/magnus.png",
    },
    {
      name: "HAND CANNON",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/handcannon.png",
    },
    {
      name: "SHOTGUN",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN", "BLAST"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/shotgun.png",
    },
    {
      name: "WINCHESTER",
      type: "ranged",
      usage: ["EFFECT", "EFFECT", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/winchester.png",
    },
    {
      name: "TEC 9",
      type: "ranged",
      usage: ["EFFECT", "EFFECT", "EFFECT", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN", "BURST"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/tec9.png",
    },
    {
      name: "SCORPION",
      type: "ranged",
      usage: ["EFFECT", "EFFECT", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN", "BURST"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/scorpion.png",
    },
    {
      name: "M-16",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN", "BURST"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/m16.png",
    },
    {
      name: "AK47",
      type: "ranged",
      usage: ["QUALITY", "QUALITY", "QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["GUN", "BURST"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/ak47.png",
    },
    {
      name: "M29-LMG",
      type: "ranged",
      usage: ["EFFECT", "EFFECT", "QUALITY", "DURABILITY", "QUALITY", "DURABILITY", "QUALITY", "QUALITY"],
      damageTypes: ["BURST"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/PEO_M249_Para_ACOG.jpg",
    },
    {
      name: "AUTOCANNON",
      type: "ranged",
      usage: ["QUALITY", "QUALITY", "QUALITY", "QUALITY", "QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["GUN", "PAIN", "BURST"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/Autocannon_Vraks.webp",
    },
    {
      name: "MEGIDDO MORTAR",
      type: "ranged",
      usage: ["EFFECT", "EFFECT", "QUALITY", "QUALITY", "QUALITY", "QUALITY", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["BLAST", "LIGHT"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/megiddo.png",
    },
    {
      name: "NAILGUN",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["PAIN", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/nailgun_01.png14672430-033D-4D2C-858B-E5B447482AF8Large-removebg-preview.png",
    },
    {
      name: "NECRO RIFLE",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/hellrifle.png",
    },
    {
      name: "NECRO REPEATER",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "QUALITY", "QUALITY", "DURABILITY"],
      damageTypes: ["GUN", "STAB", "BURST"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/necrorepeater.png",
    },
    {
      name: "BEAR ARBALEST",
      type: "ranged",
      usage: ["EFFECT", "QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["PAIN", "STAB"],
      hasSkill: true,
      size: false,
      horizontal: true,
      image: "img/items/bearbalest.png",
    },
    {
      name: "FRAG GRENADE",
      type: "explosive",
      usage: ["EFFECT", "EFFECT", "EFFECT", "EFFECT", "EFFECT", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["BLAST"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/grenade.png",
    },
    {
      name: "MOLOTOV COCKTAIL",
      type: "explosive",
      usage: ["EFFECT", "EFFECT", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "LIGHT"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/molotov.png",
    },
    {
      name: "SHOCK",
      type: "magic",
      usage: [],
      damageTypes: ["VOLT"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/bolt.png), url(img/items/rune.png",
    },
    {
      name: "ANEURYSM",
      type: "magic",
      usage: [],
      damageTypes: ["NEURAL"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/brainbleed.png), url(img/items/rune.png",
    },
    {
      name: "VILE MUTAGEN",
      type: "magic",
      usage: [],
      damageTypes: ["OOZE"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/cancer-delande-celler-iStock-removebg-preview.png), url(img/items/rune.png",
    },
    {
      name: "ENFLAME",
      type: "magic",
      usage: [],
      damageTypes: ["LIGHT"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/enflame.png), url(img/items/rune.png",
    },
    {
      name: "IRRADIATE",
      type: "magic",
      usage: [],
      damageTypes: ["OOZE"],
      hasSkill: true,
      size: false,
      horizontal: false,
      image: "img/items/Plutonium_pellet-removebg-preview.png), url(img/items/rune.png",
    },
    {
      name: "RATIONS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/rations.png",
    },
    {
      name: "FRESH FRUITS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/frutas_4-removebg-preview.png",
    },
    {
      name: "WATER",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/aqua.jpg",
    },
    {
      name: "CAPRISUN",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/caprisun.jpg",
    },
    {
      name: "NAILS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/nails.png",
    },
    {
      name: "ADHESIVE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/adhesive.png",
    },
    {
      name: "TAPE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/tape.png",
    },
    {
      name: "COPPER WIRE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/copperwire.png",
    },
    {
      name: "SENSORS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/sensors.png",
    },
    {
      name: "TIMER",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/timer.png",
    },
    {
      name: "REMOTE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/remote.png",
    },
    {
      name: "MEDICINE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/meds.png",
    },
    {
      name: "FIRST AID KIT",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/aidkit.png",
    },
    {
      name: "INFLATABLE BOAT",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: true,
      image: "img/items/boat.png",
    },
    {
      name: "CAR BATTERY",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/carbattery.png",
    },
    {
      name: "CIGARETTES",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/cigarettes.png",
    },
    {
      name: "MATCHES",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/matches.png",
    },
    {
      name: "GASOLINE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/gasoline.png",
    },
    {
      name: "CAR PARTS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/carparts.png",
    },
    {
      name: "GEIGER COUNTER",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/geiger.jpg",
    },
    {
      name: "PORTABLE STILL",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/still.jpg",
    },
    {
      name: "TENT",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/tent.jpg",
    },
    {
      name: "VIALS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/vials.png",
    },
    {
      name: "ACID",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/acid.webp",
    },
    {
      name: "CHEMICALS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/ricca-solvents-removebg-preview.png",
    },
    {
      name: "PARACHUTE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/download.jpg",
    },
    {
      name: "OFFICE SUPPLIES",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/office.png",
    },
    {
      name: "EXPLOSIVES",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/explosives.png",
    },
    {
      name: "CHEWING GUM",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/chewinggum.png",
    },
    {
      name: "BUCKET",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bucket.png",
    },
    {
      name: "STEAK",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/Ribeye_Steak_Lip-on-removebg-preview.png",
    },
    {
      name: "WATER DISPENSER",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/water.png",
    },
    {
      name: "PAPER MONEY",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/history-of-paper-money-removebg-preview.png",
    },
    {
      name: "REGENERATIUM",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/syringe.medical_512-removebg-preview.png",
    },
    {
      name: "AMPHETAMINES",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/amphetamine.png",
    },
    {
      name: "HALLUCINOGENS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/lsd.png",
    },
    {
      name: "OPIOIDS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/Opium-100glas-removebg-preview.png",
    },
    {
      name: "BOOZE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bottle-of-booze-700-189084535-removebg-preview.png",
    },
    {
      name: "AMMO",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/ammo.png",
    },
    {
      name: "BINOCULARS",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/binoculars.png",
    },
    {
      name: "EXPANDABLE SOLAR",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/solar.png",
    },
    {
      name: "EXPANDABLE TURBINE",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/windturbine.png",
    },
    {
      name: "BURNER GENERATOR",
      type: "stuff",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/generator.png",
    },
    {
      name: "HOCKEY MASK",
      type: "headgear",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/hocketmask.png",
    },
    {
      name: "ROAD HELMET",
      type: "headgear",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/motorbikehelmet.jfif",
    },
    {
      name: "BIKE HELMET",
      type: "headgear",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bikehelmet.jpg",
    },
    {
      name: "HARDHAT",
      type: "headgear",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/hardhat.jpg",
    },
    {
      name: "GAS MASK",
      type: "headgear",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: ["OOZE"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/gasmask.jpg",
    },
    {
      name: "GOGGLES",
      type: "headgear",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: ["*"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/goggles.png",
    },
    {
      name: "SKULL HELMET",
      type: "headgear",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["PAIN"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/skull.png",
    },
    {
      name: "TINFOIL HAT",
      type: "headgear",
      usage: ["DURABILITY"],
      damageTypes: ["NEURAL"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/tinfoilhat.png",
    },
    {
      name: "KEVLAR VEST",
      type: "armor",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["GUN"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/kevlar.jpg",
    },
    {
      name: "HOCKEY ARMOR",
      type: "armor",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["SMASH"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/hockeyarmor.png",
    },
    {
      name: "LEATHER VEST",
      type: "armor",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["PAIN"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/leather.png",
    },
    {
      name: "METAL PLATE",
      type: "armor",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["CUT"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/metalplate-removebg-preview.png",
    },
    {
      name: "RIOT SHIELD",
      type: "shield",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["BLAST"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/riotshield.jfif",
    },
    {
      name: "STOP SIGN",
      type: "shield",
      usage: ["QUALITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["STAB"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/stopshield.jpg",
    },
    {
      name: "PLANKS WITH GRIP",
      type: "shield",
      usage: ["QUALITY", "DURABILITY"],
      damageTypes: ["VOLT"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/plank.png",
    },
    {
      name: "MARINE ARMOR",
      type: "armor",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["BURST", "BLAST"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/armor-combat.png",
    },
    {
      name: "COMBAT ARMOR",
      type: "armor",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["NUKE", "LIGHT"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/combat-armor.jfif",
    },
    {
      name: "BULL ARMOR",
      type: "armor",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["OOZE", "NEURAL"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/poweredarmor.jpg",
    },
    {
      name: "SHELL ARMOR",
      type: "armor",
      usage: ["QUALITY", "QUALITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["GUN", "LIGHT"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/shellarmor.png",
    },
    {
      name: "HAZMAT SUIT",
      type: "armor",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "OOZE", "NUKE", "VOLT"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/hazmat.png",
    },
    {
      name: "CAMOUFLAGE",
      type: "armor",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "PAIN"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/kamouflage-och-maskering-ghillie-suit-woodland-44574-f1-removebg-preview.png",
    },
    {
      name: "ARCTIC GEAR",
      type: "armor",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["*", "CUT", "SMASH"],
      hasSkill: false,
      size: true,
      horizontal: false,
      image: "img/items/arctic.png",
    },
    {
      name: "GRAPPLER",
      type: "cybernetics",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["CUT", "PAIN", "SMASH"],
      hasSkill: false,
      size: false,
      horizontal: true,
      image: "img/items/grapplehand.png",
    },
    {
      name: "BIONIC ARM",
      type: "cybernetics",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: ["PAIN", "SMASH"],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bionicarm.png",
    },
    {
      name: "BIONIC LEG",
      type: "cybernetics",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bionicleg.png",
    },
    {
      name: "BIONIC EYE",
      type: "cybernetics",
      usage: ["QUALITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bioniceye.png",
    },
    {
      name: "POLYGEL",
      type: "artifact",
      usage: ["DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/polygel.png",
    },
    {
      name: "BIO-SCANNER",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/bio-scanner.png",
    },
    {
      name: "NEURO-ANIMATOR",
      type: "artifact",
      usage: ["DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/neuro-animator.png",
    },
    {
      name: "GATE RECOILER",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: true,
      image: "img/items/teleport-thumb-1.jpg",
    },
    {
      name: "X-RAY BEAM",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/x-ray.png",
    },
    {
      name: "SOLAR CONDENSER",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/solarcondenser.png",
    },
    {
      name: "ROCKET SKATES",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/rocketskates.png",
    },
    {
      name: "FOAMCRETE DISPENSER",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/foamgel.png",
    },
    {
      name: "2-DIMENSIONAL SUIT",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/2d.png",
    },
    {
      name: "MAG BOOTS",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/magboots.png",
    },
    {
      name: "ANTI-GRAV BOOTS",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/antigrav.png",
    },
    {
      name: "COPTER PACK",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/copterpack.png",
    },
    {
      name: "GROWGEL INJECTOR",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/growgel.png",
    },
    {
      name: "SLAVE CROWN",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/slavecrown.png",
    },
    {
      name: "LASER SCULPTER",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/lasersculpter.png",
    },
    {
      name: "THERMOBARIC CELL",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/thermobariccell.png",
    },
    {
      name: "AUTODOC",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/autodoc.png",
    },
    {
      name: "LIFEFORM SENSOR",
      type: "artifact",
      usage: ["DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY", "DURABILITY"],
      damageTypes: [],
      hasSkill: false,
      size: false,
      horizontal: false,
      image: "img/items/lifeformsensor.png",
    },
  ];
  for (var item of items) {
    item.textClass = "";
    if (item.name.length > 8) item.textClass = "small";
    if (item.name.length > 11) item.textClass = "smaller";
    if (item.name.length > 14) item.textClass = "smallest";
  }
  return items;
}
