function getNames() {
  return {
    maleFirstNames: getMaleNames(),
    femaleFirstNames: getFemaleNames(),
    lastNames: getLastNames(),
    titles: getTitles(),
    banditNames: getBanditNames(),
    hipsterNames: getHipsterNames(),
    shopNames: getShopNames(),
    tavernNames: getTavernNames(),
    nickNames: getNickNames(),
    virtues: getVirtues(),
    vices: getVices(),
    flaws: getFlaws(),
    weather: [
      "Clear",
      "Clear",
      "Cloud",
      "Cloud",
      "Heavy overcast",
      "Wind",
      "Wind",
      "Rain",
      "Rain",
      "Thunder",
      "Thunder",
      "Storm",
      "Thunderstorm",
      "Heatwave",
      "Cold snap",
    ],
  };
}
